version: '3.8'
services:
  movies:
    image: 1siva4/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: 1siva4/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: 1siva4/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: 1siva4/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3

